# Generated by Django 4.0.3 on 2022-05-01 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('postalCode', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='users.address')),
                ('informationId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('cin', models.CharField(blank=True, max_length=8, unique=True)),
                ('passport', models.CharField(blank=True, max_length=7)),
                ('nationality', models.CharField(max_length=30)),
                ('date_of_Birth', models.DateField(blank=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=30)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            bases=('users.address', models.Model),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('information_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='users.information')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('patientId', models.AutoField(primary_key=True, serialize=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=200, null=True)),
                ('occupation', models.CharField(max_length=100)),
                ('chronic_disease', models.CharField(blank=True, max_length=100)),
                ('allergy', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.information', models.Model),
        ),
    ]
