# Generated by Django 4.0.3 on 2022-04-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_allergy_user_chronic_disease_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_stuff',
            field=models.BooleanField(default=False),
        ),
    ]
