# Generated by Django 2.2.27 on 2022-04-30 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('postalCode', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.AutoField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('fileId', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientId', models.AutoField(primary_key=True, serialize=False)),
                ('occupation', models.CharField(max_length=100)),
                ('chronic_disease', models.CharField(max_length=100)),
                ('allergy', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='EmployeeApp.File')),
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EmployeeApp.Address')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('cin', models.CharField(max_length=8)),
                ('passport', models.CharField(max_length=7)),
                ('nationality', models.CharField(max_length=30)),
                ('date_of_Birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=30)),
            ],
            bases=('EmployeeApp.address', 'EmployeeApp.file'),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultationId', models.AutoField(primary_key=True, serialize=False)),
                ('appointmentDate', models.DateField()),
                ('appointmentState', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], max_length=30)),
                ('prescriptionImage', models.ImageField(blank=True, null=True, upload_to='auth/uploads/consultation_image')),
                ('prescriptionText', models.CharField(blank=True, max_length=100, null=True)),
                ('doctorNotes', models.CharField(blank=True, max_length=100, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('bloodPressure', models.FloatField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='EmployeeApp.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='info_patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.Information'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('information_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='EmployeeApp.Information')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('employeeId', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('doctor', 'doctor'), ('analysist', 'analysist'), ('radiologist', 'radiologist'), ('pharmacist', 'pharmacist'), ('secretary', 'secretary')], max_length=30)),
                ('speciality', models.CharField(max_length=50)),
                ('dateOfJoining', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.Department')),
                ('patients', models.ManyToManyField(blank=True, null=True, related_name='staff_medical', to='EmployeeApp.Patient')),
            ],
            options={
                'abstract': False,
            },
            bases=('EmployeeApp.information', models.Model),
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('RadioId', models.AutoField(primary_key=True, serialize=False)),
                ('radio_image', models.ImageField(upload_to='')),
                ('radiologistNotes', models.CharField(max_length=100)),
                ('doctorNotes', models.CharField(max_length=100)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.Consultation')),
                ('radiologist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('AnalysisId', models.AutoField(primary_key=True, serialize=False)),
                ('Analysis_image', models.ImageField(upload_to='')),
                ('AnalystNotes', models.CharField(max_length=100)),
                ('doctorNotes', models.CharField(max_length=100)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.Consultation')),
                ('analyst', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
