# Generated by Django 2.2.27 on 2022-04-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='analyst',
        ),
    ]
