# Generated by Django 4.0.3 on 2022-04-19 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeId', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('doctor', 'doctor'), ('analysist', 'analysist'), ('biologist', 'biologist'), ('pharmacist', 'pharmacist'), ('secretary', 'secretary')], max_length=30)),
                ('speciality', models.CharField(max_length=50)),
                ('dateOfJoining', models.DateField()),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.department')),
                ('info_Employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.information')),
                ('patients', models.ManyToManyField(to='EmployeeApp.patient')),
            ],
        ),
    ]
