# Generated by Django 4.0.3 on 2022-04-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('PatientsId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Email_Address', models.EmailField(max_length=254)),
                ('Telephone', models.IntegerField(max_length=8)),
                ('CIN', models.IntegerField(max_length=8)),
                ('Address', models.CharField(max_length=100)),
                ('Sexe', models.CharField(max_length=10)),
                ('Date_of_Birth', models.DateField()),
                ('Occupation', models.CharField(max_length=100)),
                ('Chronic_disease', models.CharField(max_length=100)),
                ('Allergy', models.CharField(max_length=100)),
            ],
        ),
    ]
