# Generated by Django 4.0.4 on 2022-05-29 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_alter_consultation_doctor_alter_consultation_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='appointmentTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
