# Generated by Django 4.0.3 on 2022-04-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='patients',
        ),
    ]
