# Generated by Django 4.0.4 on 2022-04-23 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_consultation_employee_radio_consultation_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='EmployeeApp.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patients',
            field=models.ManyToManyField(blank=True, null=True, related_name='staff_medical', to='EmployeeApp.patient'),
        ),
    ]
