# Generated by Django 4.0.3 on 2022-04-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_alter_patients_cin_alter_patients_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='Telephone',
        ),
        migrations.AlterField(
            model_name='patients',
            name='CIN',
            field=models.CharField(max_length=8),
        ),
    ]
