# Generated by Django 2.2.27 on 2022-04-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_auto_20220430_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radio',
            name='radiologist',
        ),
    ]
