# Generated by Django 4.0.3 on 2022-04-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_remove_employee_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='patients',
            field=models.ManyToManyField(to='EmployeeApp.patient'),
        ),
    ]
