# Generated by Django 4.0.3 on 2022-04-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0004_remove_patients_telephone_alter_patients_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='Telephone',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
