# Generated by Django 2.2.27 on 2022-04-30 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0004_remove_radio_radiologist'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fileString',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
