# Generated by Django 4.0.4 on 2022-04-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0005_remove_employee_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='patients',
            field=models.ManyToManyField(to='EmployeeApp.patient'),
        ),
    ]
