# Generated by Django 2.2.27 on 2022-04-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0005_file_filestring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='fileString',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
