# Generated by Django 4.0.4 on 2022-04-21 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0006_employee_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentId', models.AutoField(primary_key=True, serialize=False)),
                ('appointmentDate', models.DateField()),
                ('appointmentState', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], max_length=30)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultationId', models.AutoField(primary_key=True, serialize=False)),
                ('prescriptionText', models.CharField(max_length=100)),
                ('doctorNotes', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('bloodPressure', models.FloatField()),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.patient')),
            ],
        ),
    ]
