# Generated by Django 2.2.27 on 2022-04-15 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0006_rename_sexe_patients_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('postelCode', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('AnalysisId', models.AutoField(primary_key=True, serialize=False)),
                ('Analysis_image', models.ImageField(upload_to='')),
                ('AnalystNotes', models.CharField(max_length=100)),
                ('doctorNotes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentId', models.AutoField(primary_key=True, serialize=False)),
                ('appointmentDate', models.DateField()),
                ('appointmentState', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultationId', models.AutoField(primary_key=True, serialize=False)),
                ('prescriptionImage', models.ImageField(upload_to='')),
                ('prescriptionText', models.CharField(max_length=100)),
                ('doctorNotes', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('bloodPressure', models.FloatField()),
                ('analysisList', models.ManyToManyField(to='EmployeeApp.Analysis')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('cin', models.CharField(max_length=8)),
                ('passport', models.CharField(max_length=7)),
                ('nationality', models.CharField(max_length=30)),
                ('date_of_Birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=30)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('RadioId', models.AutoField(primary_key=True, serialize=False)),
                ('radio_image', models.ImageField(upload_to='')),
                ('radiologistNotes', models.CharField(max_length=100)),
                ('doctorNotes', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='Patients',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='DepartmentId',
            new_name='departmentId',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='DepartmentName',
            new_name='departmentName',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('information_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='EmployeeApp.Information')),
                ('employeeId', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(max_length=50)),
                ('speciality', models.CharField(max_length=50)),
                ('dateOfJoining', models.DateField()),
            ],
            bases=('EmployeeApp.information',),
        ),
        migrations.AddField(
            model_name='consultation',
            name='radioList',
            field=models.ManyToManyField(to='EmployeeApp.Radio'),
        ),
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.AddField(
            model_name='radio',
            name='radiologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.Employee'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('information_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='EmployeeApp.Information')),
                ('patientsId', models.AutoField(primary_key=True, serialize=False)),
                ('Occupation', models.CharField(max_length=100)),
                ('Chronic_disease', models.CharField(max_length=100)),
                ('Allergy', models.CharField(max_length=100)),
                ('appointments', models.ManyToManyField(to='EmployeeApp.Appointment')),
                ('consultations', models.ManyToManyField(to='EmployeeApp.Consultation')),
                ('medical_staff_Patient', models.ManyToManyField(to='EmployeeApp.Employee')),
            ],
            bases=('EmployeeApp.information',),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.Department'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.Employee'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='analyst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.Employee'),
        ),
    ]
