# Generated by Django 4.0.4 on 2022-04-22 00:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0007_appointment_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='prescriptionImage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('RadioId', models.AutoField(primary_key=True, serialize=False)),
                ('radio_image', models.ImageField(upload_to='')),
                ('radiologistNotes', models.CharField(max_length=100)),
                ('doctorNotes', models.CharField(max_length=100)),
                ('radiologist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('AnalysisId', models.AutoField(primary_key=True, serialize=False)),
                ('Analysis_image', models.ImageField(upload_to='')),
                ('AnalystNotes', models.CharField(max_length=100)),
                ('doctorNotes', models.CharField(max_length=100)),
                ('analyst', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.employee')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='analysisList',
            field=models.ManyToManyField(to='EmployeeApp.analysis'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='radioList',
            field=models.ManyToManyField(to='EmployeeApp.radio'),
        ),
    ]
