# Generated by Django 4.0.4 on 2022-04-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0011_remove_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ManyToManyField(to='EmployeeApp.employee'),
        ),
    ]
