# Generated by Django 4.0.4 on 2022-04-22 01:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0012_appointment_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.employee'),
            preserve_default=False,
        ),
    ]
